import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { TailwindThemeProvider } from "@/components/theme-provider"
import "@splidejs/react-splide/css";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Animekun",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head>
				<link rel="icon" href="/images/favicon.ico" type="any"></link>
			</head>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-450 mx-auto`}>
				<TailwindThemeProvider>
					{children}
				</TailwindThemeProvider>
			</body>
		</html>
	);
}
